### ISSUE TITLE
gd2 crash while detaching and attaching a peer (external etcd)

### ISSUE THREAD

**Issue by sac-urs** [gluster/glusterd2#1012]
Setup:

Two servers, with external etcd running on both of them. The etcd configuration looks like:

```
data-dir: "/var/lib/etcd"
listen-peer-urls: http://10.70.41.250:2380
listen-client-urls: http://10.70.41.250:2379
name: "glusterd2"
initial-advertise-peer-urls: http://10.70.41.250:2380
advertise-client-urls: http://10.70.41.250:2379
```

glusterd2 is started on both the servers, with each server pointing to etcd on it. The gd2 configuration looks like:

```
localstatedir = "/usr/local/var/lib/glusterd2"
logdir = "/usr/local/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/usr/local/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
etcdendpoints="http://10.70.41.250:2379"
noembed = true
resauth = true
```

When the run the steps:

1. peer add
2. peer list
3. peer remove
4. peer add

glusterd2 crashes with message

```
2018-07-13 15:17:39.879921 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:2379: connect: connection refused"; Reconnecting to {localhost:2379 <nil>}                                                     
2018-07-13 15:17:40.878899 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:2379: connect: connection refused"; Reconnecting to {localhost:2379 <nil>}                                                     
2018-07-13 15:17:42.567411 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:2379: connect: connection refused"; Reconnecting to {localhost:2379 <nil>}                                                     
2018-07-13 15:17:44.877285 I | etcdserver/api/v3rpc: Failed to dial localhost:2379: context canceled; please retry.                                 

panic: close of closed channel

goroutine 226 [running]:
github.com/gluster/glusterd2/glusterd2/events.stopLivenessWatcher()
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/events/liveness.go:77 +0x30                                                
github.com/gluster/glusterd2/glusterd2/events.Stop(0xc4200178d0, 0x1)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/events/events.go:51 +0x22                                                  
github.com/gluster/glusterd2/glusterd2/commands/peers.ReconfigureStore(0xc420195a40, 0x0, 0x0)                                                      
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:161 +0x8b                                   
github.com/gluster/glusterd2/glusterd2/commands/peers.(*PeerService).Join(0xc4200b9e68, 0x10b9180, 0xc42090cb70, 0xc42090cc00, 0x0, 0x0, 0x0)       
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc-svc.go:83 +0x3b6                                   
github.com/gluster/glusterd2/glusterd2/commands/peers._PeerService_Join_Handler(0xe94ac0, 0xc4200b9e68, 0x10b9180, 0xc42090cb70, 0xc42070e730, 0x0, 0x0, 0x0, 0x7f6ed689a300, 0x0)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/glusterd2/commands/peers/peer-rpc.pb.go:209 +0x241                                   
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4206b20c0, 0x10bf160, 0xc4207ffef0, 0xc4206b6ff0, 0xc42090d590, 0x17d4260, 0xc42090cb40, 0x0, 0x0)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:638 +0x8f3                                   
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4206b20c0, 0x10bf160, 0xc4207ffef0, 0xc4206b6ff0, 0xc42090cb40)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:796 +0x1052                                  
github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420805420, 0xc4206b20c0, 0x10bf160, 0xc4207ffef0, 0xc4206b6ff0)
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:449 +0x9f                                    
created by github.com/gluster/glusterd2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1                                                  
        /home/sac/work/golang/src/github.com/gluster/glusterd2/vendor/google.golang.org/grpc/server.go:447 +0xa1                                    
[root@dhcp43-250 build]#
```

Attaching logs.
[server1.log](https://github.com/gluster/glusterd2/files/2192367/server1.log)
[server2.log](https://github.com/gluster/glusterd2/files/2192368/server2.log)

**Comment by sac-urs** [comment]
The issue persists with single etcd server as well. The config file on both the nodes:

Server1:

```
ocalstatedir = "/usr/local/var/lib/glusterd2"
logdir = "/usr/local/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/usr/local/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
etcdendpoints="http://10.70.41.250:2379"
noembed = true
resauth = true
```


Server2:
```
localstatedir = "/usr/local/var/lib/glusterd2"
logdir = "/usr/local/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/usr/local/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
etcdendpoints="http://10.70.41.250:2379"
noembed = true
resauth = true
```

Both pointing to same etcd server.
