### ISSUE TITLE
gd2 smoke: gd2 failed to start

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#1221]
```log
08:59:01 === RUN   TestBitrot
08:59:05 === RUN   TestBitrot/Replica-volume
08:59:05 === RUN   TestBitrot/Dist-volume
08:59:08 --- FAIL: TestBitrot (6.70s)
08:59:08     --- FAIL: TestBitrot/Replica-volume (0.06s)
08:59:08     	require.go:765: 
08:59:08     			Error Trace:	bitrot_test.go:67
08:59:08     			            				utils_test.go:33
08:59:08     			Error:      	Expected nil, but got: &errors.errorString{s:"Transaction step vol-create.StoreVolume failed on peer cf5f6ccf-0b94-4f0e-95e8-40d575e8c674 with error: xlator not found: sdfs\n"}
08:59:08     			Test:       	TestBitrot/Replica-volume
08:59:08     --- FAIL: TestBitrot/Dist-volume (0.05s)
08:59:08     	require.go:765: 
08:59:08     			Error Trace:	bitrot_test.go:106
08:59:08     			            				utils_test.go:33
08:59:08     			Error:      	Expected nil, but got: &errors.errorString{s:"Transaction step vol-create.StoreVolume failed on peer cf5f6ccf-0b94-4f0e-95e8-40d575e8c674 with error: xlator not found: sdfs\n"}
08:59:08     			Test:       	TestBitrot/Dist-volume
08:59:08 === RUN   TestGeorepCreateDelete
08:59:13 --- FAIL: TestGeorepCreateDelete (5.61s)
08:59:13 	require.go:765: 
08:59:13 			Error Trace:	georep_test.go:50
08:59:13 			Error:      	Expected nil, but got: &errors.errorString{s:"Transaction step vol-create.StoreVolume failed on peer d9bae83c-2484-4c6d-a487-e3f50c94ceb1 with error: xlator not found: sdfs\n"}
08:59:13 			Test:       	TestGeorepCreateDelete
08:59:13 === RUN   TestSelfHeal
08:59:17 --- FAIL: TestSelfHeal (4.09s)
08:59:17 	require.go:765: 
08:59:17 			Error Trace:	glustershd_test.go:50
08:59:17 			Error:      	Expected nil, but got: &errors.errorString{s:"Transaction step vol-create.StoreVolume failed on peer fa0a6f8e-5d1d-4a91-856f-301e815f4c92 with error: xlator not found: sdfs\n"}
08:59:17 			Test:       	TestSelfHeal
08:59:17 === RUN   TestAddRemovePeer
08:59:32 --- PASS: TestAddRemovePeer (14.13s)
08:59:32 === RUN   TestRESTAPIAuth
08:59:35 --- PASS: TestRESTAPIAuth (3.04s)
08:59:35 === RUN   TestRestart
08:59:38 --- FAIL: TestRestart (2.58s)
08:59:38 	require.go:765: 
08:59:38 			Error Trace:	restart_test.go:46
08:59:38 			Error:      	Expected nil, but got: &errors.errorString{s:"Transaction step vol-create.StoreVolume failed on peer e765b629-7baa-405a-92be-b2f2b742cb09 with error: xlator not found: sdfs\n"}
08:59:38 			Test:       	TestRestart
08:59:38 === RUN   TestSmartVolume
08:59:46 --- FAIL: TestSmartVolume (8.53s)
08:59:46 	require.go:765: 
08:59:46 			Error Trace:	smartvol_ops_test.go:254
08:59:46 			Error:      	Expected nil, but got: &errors.errorString{s:"setupCluster(): Peer add failed with error response signature is invalid"}
08:59:46 			Test:       	TestSmartVolume
08:59:46 === RUN   TestSnapshot
09:00:01 --- FAIL: TestSnapshot (14.85s)
09:00:01 	require.go:765: 
09:00:01 			Error Trace:	snapshot_ops_test.go:57
09:00:01 			Error:      	Expected nil, but got: &errors.errorString{s:"Transaction step vol-create.StoreVolume failed on peer cd944c80-23e8-407e-9b62-a7fa2096a51e with error: xlator not found: sdfs\n"}
09:00:01 			Test:       	TestSnapshot
09:00:01 			Messages:   	Failed to create the volume
09:00:01 === RUN   TestVolume
09:00:05 === RUN   TestVolume/CreateWithoutName
09:00:05 === RUN   TestVolume/Create
09:00:05 === RUN   TestVolume/Expand
09:00:05 === RUN   TestVolume/Start
09:00:05 === RUN   TestVolume/Mount
09:08:59 SIGQUIT: quit
09:08:59 PC=0x45f899 m=0 sigcode=0
09:08:59 
09:08:59 goroutine 0 [idle]:
09:08:59 runtime.epollwait(0x7ffe00000004, 0x7ffef8424030, 0xffffffff00000080, 0x0, 0xffffffff00000004, 0x7ffe00000000, 0x0, 0x0, 0x0, 0x0, ...)
09:08:59 	/usr/lib/golang/src/runtime/sys_linux_amd64.s:617 +0x19
09:08:59 runtime.netpoll(0xc420027301, 0xc420027301)
09:08:59 	/usr/lib/golang/src/runtime/netpoll_epoll.go:71 +0x12c
09:08:59 runtime.findrunnable(0xc420026000, 0x0)
09:08:59 	/usr/lib/golang/src/runtime/proc.go:2117 +0x5fb
09:08:59 runtime.schedule()
09:08:59 	/usr/lib/golang/src/runtime/proc.go:2255 +0x12c
09:08:59 runtime.goexit0(0xc42006db00)
09:08:59 	/usr/lib/golang/src/runtime/proc.go:2406 +0x236
09:08:59 runtime.mcall(0x7ffef84247c0)
09:08:59 	/usr/lib/golang/src/runtime/asm_amd64.s:286 +0x5b
09:08:59 
09:08:59 goroutine 1 [chan receive, 8 minutes]:
09:08:59 testing.(*T).Run(0xc4206ac000, 0xe279d6, 0xa, 0xe5b3c0, 0x490300)
09:08:59 	/usr/lib/golang/src/testing/testing.go:790 +0x2fc
09:08:59 testing.runTests.func1(0xc4206ac000)
09:08:59 	/usr/lib/golang/src/testing/testing.go:1004 +0x64
09:08:59 testing.tRunner(0xc4206ac000, 0xc420813d80)
09:08:59 	/usr/lib/golang/src/testing/testing.go:746 +0xd0
09:08:59 testing.runTests(0xc42082a1a0, 0x134cb60, 0xb, 0xb, 0x0)
09:08:59 	/usr/lib/golang/src/testing/testing.go:1002 +0x2d8
09:08:59 testing.(*M).Run(0xc420813f18, 0x12)
09:08:59 	/usr/lib/golang/src/testing/testing.go:921 +0x111
09:08:59 github.com/gluster/glusterd2/e2e.TestMain(0xc420813f18)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/main_test.go:44 +0x219
09:08:59 main.main()
09:08:59 	github.com/gluster/glusterd2/e2e/_test/_testmain.go:62 +0xdb
09:08:59 
09:08:59 goroutine 47 [chan receive]:
09:08:59 github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4201ddc00)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x47a
09:08:59 created by github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xb8
09:08:59 
09:08:59 goroutine 53 [chan receive]:
09:08:59 github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4201dde00)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x47a
09:08:59 created by github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xb8
09:08:59 
09:08:59 goroutine 54 [chan receive]:
09:08:59 github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4201dde60)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x47a
09:08:59 created by github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xb8
09:08:59 
09:08:59 goroutine 67 [chan receive, 9 minutes]:
09:08:59 github.com/gluster/glusterd2/glusterd2/daemon.init.0.func1()
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/glusterd2/daemon/connection.go:72 +0xd0
09:08:59 created by github.com/gluster/glusterd2/glusterd2/daemon.init.0
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/glusterd2/daemon/connection.go:71 +0x35
09:08:59 
09:08:59 goroutine 572 [chan receive, 8 minutes]:
09:08:59 testing.(*T).Run(0xc4206ac0f0, 0xe22e6b, 0x5, 0xc4208c04a0, 0x0)
09:08:59 	/usr/lib/golang/src/testing/testing.go:790 +0x2fc
09:08:59 github.com/gluster/glusterd2/e2e.TestVolume(0xc4206ac0f0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/volume_ops_test.go:56 +0x31b
09:08:59 testing.tRunner(0xc4206ac0f0, 0xe5b3c0)
09:08:59 	/usr/lib/golang/src/testing/testing.go:746 +0xd0
09:08:59 created by testing.(*T).Run
09:08:59 	/usr/lib/golang/src/testing/testing.go:789 +0x2de
09:08:59 
09:08:59 goroutine 332 [syscall, 9 minutes]:
09:08:59 syscall.Syscall6(0xf7, 0x1, 0x4db7, 0xc4208195c0, 0x1000004, 0x0, 0x0, 0x20, 0x18, 0xd56420)
09:08:59 	/usr/lib/golang/src/syscall/asm_linux_amd64.s:44 +0x5
09:08:59 os.(*Process).blockUntilWaitable(0xc4205de360, 0x600208c0ea0, 0x10, 0x20)
09:08:59 	/usr/lib/golang/src/os/wait_waitid.go:31 +0xa5
09:08:59 os.(*Process).wait(0xc4205de360, 0xdf9460, 0x1, 0xc4208c0ec0)
09:08:59 	/usr/lib/golang/src/os/exec_unix.go:22 +0x42
09:08:59 os.(*Process).Wait(0xc4205de360, 0xc4208c0ec0, 0x0, 0x0)
09:08:59 	/usr/lib/golang/src/os/exec.go:115 +0x2b
09:08:59 os/exec.(*Cmd).Wait(0xc4206ab340, 0x4354e8, 0xe5e458)
09:08:59 	/usr/lib/golang/src/os/exec/exec.go:446 +0x62
09:08:59 github.com/gluster/glusterd2/e2e.(*etcdProcess).Spawn.func1(0xc420708030)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/process_utils_test.go:223 +0x2e
09:08:59 created by github.com/gluster/glusterd2/e2e.(*etcdProcess).Spawn
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/process_utils_test.go:222 +0x14a
09:08:59 
09:08:59 goroutine 574 [syscall, 8 minutes]:
09:08:59 syscall.Syscall6(0xf7, 0x1, 0x4fd9, 0xc42083bdc0, 0x1000004, 0x0, 0x0, 0x300000002, 0xc4206c8300, 0xc42083bde0)
09:08:59 	/usr/lib/golang/src/syscall/asm_linux_amd64.s:44 +0x5
09:08:59 os.(*Process).blockUntilWaitable(0xc4205df770, 0xc42083bec0, 0xc42083beb8, 0x4133fc)
09:08:59 	/usr/lib/golang/src/os/wait_waitid.go:31 +0xa5
09:08:59 os.(*Process).wait(0xc4205df770, 0xc42064e000, 0xc42083bf30, 0x4a2d13)
09:08:59 	/usr/lib/golang/src/os/exec_unix.go:22 +0x42
09:08:59 os.(*Process).Wait(0xc4205df770, 0xc42083bf90, 0x73d3bf, 0xc4201f82f8)
09:08:59 	/usr/lib/golang/src/os/exec.go:115 +0x2b
09:08:59 os/exec.(*Cmd).Wait(0xc420852c60, 0xe5e458, 0x0)
09:08:59 	/usr/lib/golang/src/os/exec/exec.go:446 +0x62
09:08:59 github.com/gluster/glusterd2/e2e.spawnGlusterd.func1(0xc4201f83c0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/process_utils_test.go:161 +0x2e
09:08:59 created by github.com/gluster/glusterd2/e2e.spawnGlusterd
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/process_utils_test.go:160 +0x40d
09:08:59 
09:08:59 goroutine 579 [syscall, 8 minutes]:
09:08:59 syscall.Syscall6(0xf7, 0x1, 0x4fe3, 0xc42081bdc0, 0x1000004, 0x0, 0x0, 0x300000002, 0xc420734180, 0xc42081bde0)
09:08:59 	/usr/lib/golang/src/syscall/asm_linux_amd64.s:44 +0x5
09:08:59 os.(*Process).blockUntilWaitable(0xc42062cf60, 0xc42081bec0, 0xc42081beb8, 0x4133fc)
09:08:59 	/usr/lib/golang/src/os/wait_waitid.go:31 +0xa5
09:08:59 os.(*Process).wait(0xc42062cf60, 0x0, 0xc42081bf30, 0x4a2d13)
09:08:59 	/usr/lib/golang/src/os/exec_unix.go:22 +0x42
09:08:59 os.(*Process).Wait(0xc42062cf60, 0xc42081bf90, 0x73d3bf, 0xc42006fd38)
09:08:59 	/usr/lib/golang/src/os/exec.go:115 +0x2b
09:08:59 os/exec.(*Cmd).Wait(0xc420853080, 0xe5e458, 0x0)
09:08:59 	/usr/lib/golang/src/os/exec/exec.go:446 +0x62
09:08:59 github.com/gluster/glusterd2/e2e.spawnGlusterd.func1(0xc4201f90e0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/process_utils_test.go:161 +0x2e
09:08:59 created by github.com/gluster/glusterd2/e2e.spawnGlusterd
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/process_utils_test.go:160 +0x40d
09:08:59 
09:08:59 goroutine 627 [syscall, 8 minutes]:
09:08:59 syscall.Syscall6(0xf7, 0x1, 0x4fed, 0xc420045bc8, 0x1000004, 0x0, 0x0, 0x7f9b9b77e2a8, 0x0, 0x0)
09:08:59 	/usr/lib/golang/src/syscall/asm_linux_amd64.s:44 +0x5
09:08:59 os.(*Process).blockUntilWaitable(0xc420656e70, 0xc420656e70, 0x0, 0x0)
09:08:59 	/usr/lib/golang/src/os/wait_waitid.go:31 +0xa5
09:08:59 os.(*Process).wait(0xc420656e70, 0xc42006faa0, 0xc4206aad38, 0x13)
09:08:59 	/usr/lib/golang/src/os/exec_unix.go:22 +0x42
09:08:59 os.(*Process).Wait(0xc420656e70, 0x0, 0x0, 0xe5e208)
09:08:59 	/usr/lib/golang/src/os/exec.go:115 +0x2b
09:08:59 os/exec.(*Cmd).Wait(0xc4206aac60, 0x0, 0x0)
09:08:59 	/usr/lib/golang/src/os/exec/exec.go:446 +0x62
09:08:59 github.com/gluster/glusterd2/e2e.mountVolume(0xc42079ae40, 0x9, 0xe25b69, 0x7, 0xc4206569c0, 0x30, 0x0, 0x0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/utils_test.go:328 +0x2b2
09:08:59 github.com/gluster/glusterd2/e2e.testMountUnmount(0xc4201442d0, 0xe25b69, 0x7, 0xc42096a6c0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/volume_ops_test.go:394 +0x162
09:08:59 github.com/gluster/glusterd2/e2e.testVolumeMount(0xc4201442d0, 0xc42096a6c0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/volume_ops_test.go:380 +0x4a
09:08:59 github.com/gluster/glusterd2/e2e.(*testCluster).wrap.func1(0xc4201442d0)
09:08:59 	/home/jenkins/root/workspace/gd2-smoke/go/src/github.com/gluster/glusterd2/e2e/utils_test.go:33 +0x3b
09:08:59 testing.tRunner(0xc4201442d0, 0xc4208c04a0)
09:08:59 	/usr/lib/golang/src/testing/testing.go:746 +0xd0
09:08:59 created by testing.(*T).Run
09:08:59 	/usr/lib/golang/src/testing/testing.go:789 +0x2de
09:08:59 
09:08:59 rax    0xfffffffffffffffc
09:08:59 rbx    0xffffffff
09:08:59 rcx    0xffffffffffffffff
09:08:59 rdx    0x80
09:08:59 rdi    0x4
09:08:59 rsi    0x7ffef8424030
09:08:59 rbp    0x7ffef8424630
09:08:59 rsp    0x7ffef8423ff0
09:08:59 r8     0x3
09:08:59 r9     0x135a2c0
09:08:59 r10    0xffffffff
09:08:59 r11    0x246
09:08:59 r12    0xc420817f68
09:08:59 r13    0xc420664a20
09:08:59 r14    0x1
09:08:59 r15    0x0
09:08:59 rip    0x45f899
09:08:59 rflags 0x246
09:08:59 cs     0x33
09:08:59 fs     0x0
09:08:59 gs     0x0
09:08:59 *** Test killed with quit: ran too long (10m0s).
```

From https://build.gluster.org/job/gd2-smoke/830/console

**Comment by prashanthpai** [comment]
This did not fail on master branch but on a glusterfs patch.

**Comment by prashanthpai** [comment]
This did not fail on master branch but on a glusterfs patch submitted for review.
