### ISSUE TITLE
glustercli panics when given a volume create command

### ISSUE THREAD

**Issue by phlogistonjohn** [gluster/glusterd2#697]
glustercli should never panic, rather it should print a reasonable error message about why the input was not valid (or accept the input).

```bash
$ ./build/glustercli --glusterd-port 23007  volume create  /tmp/TestVolume343154490/brick014378530/  /tmp/TestVolume343154490/brick374001060/ xxx
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gluster/glusterd2/glustercli/cmd.bricksAsUUID(0xc420016510, 0x2, 0x4, 0x4cca6e, 0x7cbe6f, 0x7, 0x7cd08f, 0xa)
        /srv/go/src/github.com/gluster/glusterd2/glustercli/cmd/volume.go:109 +0x85b
github.com/gluster/glusterd2/glustercli/cmd.volumeCreateCmdRun(0x991940, 0xc420016500, 0x3, 0x5)
        /srv/go/src/github.com/gluster/glusterd2/glustercli/cmd/volume-create.go:58 +0x97
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).execute(0x991940, 0xc4200164b0, 0x5, 0x5, 0x991940, 0xc4200164b0)
        /srv/go/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x991720, 0xc420015660, 0x8, 0xc420010180)
        /srv/go/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).Execute(0x991720, 0x0, 0x0)
        /srv/go/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /srv/go/src/github.com/gluster/glusterd2/glustercli/main.go:14 +0x36
-bash-4.2# ./build/glustercli --glusterd-port 23007  volume create  /tmp/TestVolume343154490/brick014378530/  /tmp/TestVolume343154490/brick374001060/ xxx
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gluster/glusterd2/glustercli/cmd.bricksAsUUID(0xc420016560, 0x2, 0x4, 0x4cca6e, 0x7cb0da, 0x4, 0x7ce158, 0xd)
        /srv/go/src/github.com/gluster/glusterd2/glustercli/cmd/volume.go:109 +0x85b
github.com/gluster/glusterd2/glustercli/cmd.volumeCreateCmdRun(0x991940, 0xc420016550, 0x3, 0x5)
        /srv/go/src/github.com/gluster/glusterd2/glustercli/cmd/volume-create.go:58 +0x97
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).execute(0x991940, 0xc420016500, 0x5, 0x5, 0x991940, 0xc420016500)
        /srv/go/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x991720, 0xc420015660, 0x8, 0xc420010180)
        /srv/go/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).Execute(0x991720, 0x0, 0x0)
        /srv/go/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /srv/go/src/github.com/gluster/glusterd2/glustercli/main.go:14 +0x36
```

**Comment by aravindavk** [comment]
Above example is using volume name as last argument. It should be the first argument. Sent patch to fix the crash, but different ordering like this is not yet handled.
