### ISSUE TITLE
glusterd2 CPU usage is 100% after peer add

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#817]
In an external etcd setup, glusterd2 CPU usage shoots up to 100% right after peer add. There might be a busy loop somewhere.

**Comment by prashanthpai** [comment]
```sh
# pstack 3245
Thread 7 (Thread 0x7f351f3b2700 (LWP 3251)):
#0  runtime.futex () at /home/ppai/go/src/runtime/sys_linux_amd64.s:439
#1  0x000000000042aca2 in runtime.futexsleep (addr=0xc4201a1990, val=0, ns=-1) at /home/ppai/go/src/runtime/os_linux.go:45
#2  0x000000000041129b in runtime.notesleep (n=0xc4201a1990) at /home/ppai/go/src/runtime/lock_futex.go:151
#3  0x0000000000432e75 in runtime.stopm () at /home/ppai/go/src/runtime/proc.go:1670
#4  0x0000000000434052 in runtime.findrunnable (gp=0xc4206064b8, inheritTime=false) at /home/ppai/go/src/runtime/proc.go:2125
#5  0x0000000000434b0c in runtime.schedule () at /home/ppai/go/src/runtime/proc.go:2245
#6  0x0000000000434e26 in runtime.park_m (gp=0xc420606480) at /home/ppai/go/src/runtime/proc.go:2308
#7  0x000000000045b9eb in runtime.mcall () at /home/ppai/go/src/runtime/asm_amd64.s:286
#8  0x000000c420020000 in ?? ()
#9  0x0000000000000000 in ?? ()
Thread 6 (Thread 0x7f351fbb3700 (LWP 3250)):
#0  runtime.futex () at /home/ppai/go/src/runtime/sys_linux_amd64.s:439
#1  0x000000000042aca2 in runtime.futexsleep (addr=0xc4201a1610, val=0, ns=-1) at /home/ppai/go/src/runtime/os_linux.go:45
#2  0x000000000041129b in runtime.notesleep (n=0xc4201a1610) at /home/ppai/go/src/runtime/lock_futex.go:151
#3  0x000000000043357c in runtime.stoplockedm () at /home/ppai/go/src/runtime/proc.go:1817
#4  0x0000000000434caf in runtime.schedule () at /home/ppai/go/src/runtime/proc.go:2203
#5  0x0000000000434e26 in runtime.park_m (gp=0xc4206cfe00) at /home/ppai/go/src/runtime/proc.go:2308
#6  0x000000000045b9eb in runtime.mcall () at /home/ppai/go/src/runtime/asm_amd64.s:286
#7  0x000000c420020000 in ?? ()
#8  0x0000000000000000 in ?? ()
Thread 5 (Thread 0x7f3520514700 (LWP 3249)):
#0  runtime.futex () at /home/ppai/go/src/runtime/sys_linux_amd64.s:439
#1  0x000000000042aca2 in runtime.futexsleep (addr=0x1848c40 <runtime.sig>, val=0, ns=-1) at /home/ppai/go/src/runtime/os_linux.go:45
#2  0x0000000000411386 in runtime.notetsleep_internal (n=0x1848c40 <runtime.sig>, ns=-1, ~r2=53) at /home/ppai/go/src/runtime/lock_futex.go:174
#3  0x000000000041159a in runtime.notetsleepg (n=0x1848c40 <runtime.sig>, ns=-1, ~r2=240) at /home/ppai/go/src/runtime/lock_futex.go:228
#4  0x0000000000445056 in os/signal.signal_recv (~r0=4412184) at /home/ppai/go/src/runtime/sigqueue.go:131
#5  0x0000000000ca6e42 in os/signal.loop () at /home/ppai/go/src/os/signal/signal_unix.go:22
#6  0x000000000045e631 in runtime.goexit () at /home/ppai/go/src/runtime/asm_amd64.s:2337
#7  0x0000000000000000 in ?? ()
Thread 4 (Thread 0x7f3520d15700 (LWP 3248)):
#0  runtime.epollwait () at /home/ppai/go/src/runtime/sys_linux_amd64.s:576
#1  0x000000000042ab2c in runtime.netpoll (block=true, ~r1=0xc420021301) at /home/ppai/go/src/runtime/netpoll_epoll.go:71
#2  0x000000000043417b in runtime.findrunnable (gp=0xf60ce0, inheritTime=false) at /home/ppai/go/src/runtime/proc.go:2107
#3  0x0000000000434b0c in runtime.schedule () at /home/ppai/go/src/runtime/proc.go:2245
#4  0x0000000000434e26 in runtime.park_m (gp=0xc420606180) at /home/ppai/go/src/runtime/proc.go:2308
#5  0x000000000045b9eb in runtime.mcall () at /home/ppai/go/src/runtime/asm_amd64.s:286
#6  0x000000c420020000 in ?? ()
#7  0x0000000000000000 in ?? ()
Thread 3 (Thread 0x7f3521516700 (LWP 3247)):
#0  runtime.typedmemclr (typ=0xf5ed60, ptr=0xc4205a2ea8) at /home/ppai/go/src/runtime/mbarrier.go:422
#1  0x000000000043ea52 in runtime.selectgo (sel=0xc4205a2f10, ~r1=842356403296) at /home/ppai/go/src/runtime/select.go:605
#2  0x0000000000cbdb12 in github.com/gluster/glusterd2/glusterd2/events.(*livenessWatcher).Watch (l=0xc4208da600) at /home/ppai/work/src/github.com/gluster/glusterd2/glusterd2/events/liveness.go:33
#3  0x000000000045e631 in runtime.goexit () at /home/ppai/go/src/runtime/asm_amd64.s:2337
#4  0x000000c4208da600 in ?? ()
#5  0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7f3521d17700 (LWP 3246)):
#0  runtime.usleep () at /home/ppai/go/src/runtime/sys_linux_amd64.s:98
#1  0x0000000000439138 in runtime.sysmon () at /home/ppai/go/src/runtime/proc.go:3839
#2  0x0000000000431eee in runtime.mstart1 () at /home/ppai/go/src/runtime/proc.go:1172
#3  0x0000000000431dc4 in runtime.mstart () at /home/ppai/go/src/runtime/proc.go:1142
#4  0x0000000000d6f123 in crosscall_amd64 () at gcc_amd64.S:35
#5  0x00007f3521d179c0 in ?? ()
#6  0x00007fff6cbc64f0 in ?? ()
#7  0x0000000000000000 in ?? ()
Thread 1 (Thread 0x7f3522727740 (LWP 3245)):
#0  runtime.futex () at /home/ppai/go/src/runtime/sys_linux_amd64.s:439
#1  0x000000000042ad17 in runtime.futexsleep (addr=0x18247c0 <runtime.timers+32>, val=0, ns=393679498) at /home/ppai/go/src/runtime/os_linux.go:62
#2  0x0000000000411430 in runtime.notetsleep_internal (n=0x18247c0 <runtime.timers+32>, ns=393679498, ~r2=23) at /home/ppai/go/src/runtime/lock_futex.go:193
#3  0x000000000041159a in runtime.notetsleepg (n=0x18247c0 <runtime.timers+32>, ns=393679498, ~r2=false) at /home/ppai/go/src/runtime/lock_futex.go:228
#4  0x000000000044d535 in runtime.timerproc () at /home/ppai/go/src/runtime/time.go:216
#5  0x000000000045e631 in runtime.goexit () at /home/ppai/go/src/runtime/asm_amd64.s:2337
#6  0x0000000000000000 in ?? ()
```

Initial glance is pointing at `/home/ppai/work/src/github.com/gluster/glusterd2/glusterd2/events/liveness.go:34`.
